### ISSUE TITLE
Improving cross-platform support

### ISSUE THREAD

**Issue by arfy8820** [njaremko/podcast#1]
Currently, podcast seems to assume that it'll be running on a unix-style environment. I have some ideas, and have already begun playing with the code a little to enhance support for, in particular, windows. Here are the ideas I propose.

* instead of just using the title of an episode directly as the filename, do some replacements, as follows. Replace ?, *, :, and / with _.
* For some reason, most times on windows, podcast won't run, because .subscriptions.tmp can't be renamed to .subscriptions, which is being held open in the State::save() function. this somehow works on unix.

Keep up the good work!

**Comment by njaremko** [comment]
Neat, my first issue.

I've pushed a new version that escapes filenames and might fix the issue you're experiencing on Windows. I haven't really tested `podcast` on Windows, so I appreciate you letting me know. Are there any other issues you've noticed? (Doesn't have to be specific to windows)

**Comment by arfy8820** [comment]
Awesome! This seems to work perfectly. And you fixed the windows rename issue exactly how I would have done it, just by scoping the file access in State::new(). I have one very minor suggested change, I don’t have a mac to verify, but mac’s don’t allow : in filenames. Thus.
Change:
#[cfg(target_os = "macos")]
static ESCAPE_REGEX: &str = r"/";
to:
#[cfg(target_os = "macos")]
static ESCAPE_REGEX: &str = r"[/:]";

very good work!

**Comment by njaremko** [comment]
`:` was only illegal on classic macOS. The only illegal characters in filenames on linux and mac are `/` and `\0`
