### ISSUE TITLE
Add an example of $PODCAST/.subscriptions.json file in documentation

### ISSUE THREAD

**Issue by SansGuidon** [njaremko/podcast#13]
I'm trying to tell podcast to download only the latest episodes of new feeds I'm subscribing to.
it seems doable but I can't find an example of `.subscriptions.json` config nor a way to initiate it from podcast CLI.

my use case : I would like to configure podcast before it starts to download too much episodes (the feeds I'm trying to subscribe to contain tens or hundreds of episodes :-) )

Thanks in advance 💚

**Comment by njaremko** [comment]
By default, when you subscribe to a podcast, you'll only download the latest episode, then from that point on, any new episodes will also be automatically downloaded (which sounds like what you want?)

Unless you're saying that if you subscribe to a podcast, and they release 10 episodes since you last ran the CLI, you want to only download the latest one?

**Comment by SansGuidon** [comment]
I think I was confused by the UX :-) and by the docs; indeed it seems that podcast only download one episode. When I saw that podcast would automatically start downloading episodes before I decide which one I want to use, I was a bit surprised. I hate downloading data I don't need, and there are podcasts I subscribe only to listen to specific episodes, not the latest one. I guess my habits differ from yours. 

To better explain my confusion : I'm using another similar podcast management CLI tool -- castero -- its allows me to only download episodes when I play them, which is I guess more convenient for me, and I was expecting that podcast tool would empower me to do something close to that, but I understand that it's not really the case by design, so the issue can be closed.

**Comment by njaremko** [comment]
If you open `$PODCAST/.subscriptions.json` you can set:

`auto_download_limit` - The number of episodes to automatically download when you first subscribe
`download_subscription_limit` - When updating subscriptions, download this many new episodes, starting from latest

**Comment by SansGuidon** [comment]
Thank you for the feedback
I don't have such file in my default Podcasts folder, I can create one manually, then my question is : what should the file content looks like (I want to get it right), is there any example of default config ?
Thanks in advance, @njaremko :-)

**Comment by njaremko** [comment]
Have you never run the CLI? It's generated on your first run. Note that it's a hidden file.

**Comment by SansGuidon** [comment]
Mmm, it seems I've overlooked to check for hidden file and thus assumed that file was not generated. It's indeed in the right folder, thanks @njaremko !
