### ISSUE TITLE
Filename pattern

### ISSUE THREAD

**Issue by mrzv** [njaremko/podcast#18]
It would be nice if there was a way to specify the pattern for the filenames saved under the `Podcast` folder. In particular, I'd like to be able to easily sort the files by naming them `001-episode title.mp3`, `002-episode title.mp3`, etc.

**Comment by njaremko** [comment]
I can definitely add the ability to define a template specifying where the episode name and episode number should be saved, but beyond that things get a bit tricky

**Comment by mrzv** [comment]
That would already be a big improvement from my point of view.

**Comment by njaremko** [comment]
Update to `0.19.4` and you can either add it to the config file, or use 
```sh
podcast download <podcast name> <ep> -t "{number}-{title}"
```

**Comment by mrzv** [comment]
Thanks for this! Can you explain how to add this to the config file?

**Comment by njaremko** [comment]
Set `config["filename_pattern"]` in `~/Podcasts/.subscriptions.json`

**Comment by mrzv** [comment]
Is it possible to make this customizable in the config for each podcast?
