### ISSUE TITLE
Suggestion: support `sox` for non-gui podcast playback

### ISSUE THREAD

**Issue by shakfu** [njaremko/podcast#19]
Hi @njaremko 

Very cool project. Many thanks for sharing (-:

I installed `podcast` on a headless raspberry pi zero 2 connected to my mixer accessible via wifi on ssh. This works great, but the only minor issue is the lack of gui-less playback integration in `podcast play`. 

I'd rather not install `vlc` and `mpv` which require a gui or a ton of gui support packages. May I suggest to support a very popular and super useful command-line audio tool called [sox](https://sox.sourceforge.net) which has a multi-format `playback` capability (along with edit, fx, conversion, etc..) or at least allow for configuration options to support this alternative.

Thanks!

**Comment by njaremko** [comment]
Done. 

I haven't gotten around to building release artifacts in Github Actions yet, so you'll need to run
```sh
cargo update && cargo install podcast
```

**Comment by shakfu** [comment]
@njaremko 

Thanks very  much. 👍
