### ISSUE TITLE
Package podcast for Debian

### ISSUE THREAD

**Issue by robinkrahl** [njaremko/podcast#2]
I’d like to package `podcast` for Debian within the [Rust packaging team](https://wiki.debian.org/Teams/RustPackaging).  Would that be okay with you?

**Comment by njaremko** [comment]
I'm okay with it 👍

**Comment by robinkrahl** [comment]
Great! :)  It will take some time because there are some issues with `reqwest`, but I’ll comment here once the package is released.  Feel free to close this issue if you want to.

PS: [Debian tracking bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923052)

**Comment by njaremko** [comment]
In the tracking bug you specified the version, so I figured I should ping you about me making some improvements today. 

Latest version is now `0.9.1`

Also, I'm curious, how did you find this project?
