### ISSUE TITLE
Incorrect version number 0.11.0 instead of 0.12.0

### ISSUE THREAD

**Issue by teddywing** [njaremko/podcast#5]
The current release, v0.12.0, is still using v0.11.0 in:

https://github.com/njaremko/podcast/blob/aadf913/src/main.rs#L41

I think this might be confusing the update checker.

**Comment by njaremko** [comment]
Sorry for the delay. Long weekend here in Canada.

Yep, that's not good. I'll fix in a minute.

**Comment by teddywing** [comment]
> Sorry for the delay. Long weekend here in Canada.

No worries!

> Yep, that's not good. I'll fix in a minute.

Nice, thanks 👍
