### ISSUE TITLE
Download latest

### ISSUE THREAD

**Issue by smhmd** [njaremko/podcast#8]
```
$ podcast mypodcast -b 3
```
to download the latest 3 episodes, printing what is to be downloaded to stdout (whether downloading backwards or in any mode) and wait for confirmation with the information necessary to edit the command. (color, based on `.Xresources`, would be nice.)

```
$ podcast mypodcast -b 3
  1) we're celebrating 2020/01/21
  2) another episode
  3) happy new year!
  proceed[y/n]? n
$ podcast my podcast -b '1, 3'
  1) we're celebrating 2020/01/21
  3) happy new year!
  proceed[y/n]? y
```
also, please consider not logging `Using PODCAST dir: "/home/me/media/podcasts"` to sdtout, it gets annoying. (I would disable it altogether.)

**Comment by smhmd** [comment]
with `-n`/`--noconfirm` to bypass confirmation for automation.

**Comment by njaremko** [comment]
Update to 0.14.0 and set `quiet: true` in your config.yaml to remove the podcast dir print.

Also in 0.14.0, `podcast download <podcast name> -l 3` will download the latest three podcasts.

Probably going to go through and rewrite this whole project this weekend, it was hacked together to suit my needs and its a pain in the butt to add stuff to

**Comment by smhmd** [comment]
If a rewrite is due, could you please consider a TUI or at least some interactivity (move around and highlight episodes with space).
![image](https://user-images.githubusercontent.com/46059092/72854279-26be3180-3cb4-11ea-8a92-4c626c434712.png)

I sometimes want to choose to download only episodes that have to do with certain topics, having the episode description and the ability to highlight for download would cover almost all my podcast needs.

There is also a checked `Searching for podcasts` in `#currently supports` in the main README, which lead me to believe you can search for podcast RSS feed URLs from `podcast` (that would be a killer feature). should it not be `Searching for podcast episodes`?

**Comment by njaremko** [comment]
I'll look into the tui package and see about making the standard `podcast` command launch a TUI. I think it's important to support the use case of people just wanting to run a line from the command prompt to download certain podcasts (my main use case 😄 )

I had a scrapper and server setup to enable searching for podcasts by title, for example, `podcast search joe` would have printed a list containing "The Joe Rogan Experience" that you could have selected and it would have subscribed you, but nobody was using it aside from me, so I took the server down. If interest picks up again I'll start it back up.

**Comment by smhmd** [comment]
I agree with the CLI-first approach.
There is a Windows music player called [Musicbee](https://getmusicbee.com/) and they have a comprehensive take on podcast searching. The project is not OSS, but [this](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/index.html) is used if I had to guess.
![musicbee podcast searching](https://windows-cdn.softpedia.com/screenshots/MusicBee_8.png)

Also, search and search to subscribe should have different names, otherwise, they're confusing.
